- db/init.sql
- docker-compose.yml
O container do docker onde está o mysql agora está configurado para UTF-8; No arquivo init.sql agora é criado a database librorete com as entidades usuario e perfil
> close issue #5

- db/init.sql
Cria a entidade 'Lista' na database
DER da entidade:
> close issue #6

- db/init.sql
close issue #8 criando as entidades 'livro' e 'lista_livro' também possui inserções básicas
DER:
> close issue #8

- frontend/app/src/components/ListItem/ListItem.css
- frontend/app/src/components/ListItem/ListItem.jsx
- frontend/app/src/components/Lists/Lists.css
- frontend/app/src/components/Lists/Lists.jsx
- frontend/app/src/components/posts/Posts.jsx
- frontend/app/src/components/resenhas/Resenhas.jsx
- frontend/app/src/pages/Profile/Profile.css
- frontend/app/src/pages/Profile/Profile.jsx
- frontend/app/src/pages/Profile/profileRoutes.jsx
- frontend/app/src/routes.jsx
> close issue#21

- frontend/app/src/components/Lists/Lists.jsx
> close issue#7

- .github/workflows/dev.yml
Retira comentários e logs desnecessários
> update workflow dev.yml

- backend/app/tests/test_interacao.py
- db/init.sql
close issue #40 
Implementa as interações do usuário no Banco de dados
> close issue #40

- db/init.sql
Os links das imgs tem formato .png ou .jpg
> update sql imgs 

- db/init.sql
Adiciona 2 post, 15 tags e duas interações (criar post)
> add insertions

- frontend/app/src/components/bookRecommendation/BookRecommendation.css
- frontend/app/src/components/searchResults/SearchResults.css
- frontend/app/src/components/searchResults/SearchResults.jsx
- frontend/app/src/components/userRecommendation/UserRecommendation.css
- frontend/app/src/pages/CriaPost/CriaPost.css
- frontend/app/src/pages/CriaPost/CriaPost.jsx
- frontend/app/src/pages/Pesquisa/Pesquisa.css
- frontend/app/src/pages/Pesquisa/Pesquisa.jsx
> close issue#54

- backend/app/api/models.py
- backend/app/api/urls.py
- backend/app/api/views.py
- backend/app/tests/test_api.py
- backend/app/tests/test_post.py
Endpoint para listar posts de um usuário para ser usado no perfil de usuário
> Implementada funcao para listar posts de usuario

- frontend/app/package.json
- frontend/app/src/pages/CriaPost/CriaPost.css
- frontend/app/src/pages/CriaPost/CriaPost.jsx
- frontend/app/src/pages/CriaPost/CriaPost.test.js
- frontend/package-lock.json
- frontend/package.json
A integração com o endpoint de criação de post foi realizada.
Também foi criado um arquivo para teste com a biblioteca testing-library.
> close issue#53

- backend/app/api/urls.py
- backend/app/api/utils.py
- backend/app/api/views.py
> Criar e implementar algoritmo de recomendação de usuários #99 concluida

- backend/app/tests/test_criar_post.py
- backend/app/tests/test_post.py
- db/init.sql
adiciona 2 usuario, 2 perfis, 5 livros, 2 comentários, 4 posts e 14 interações
close issue#106
> close issue#106

- frontend/app/src/components/ProfilePostItem/ProfilePostItem.css
- frontend/app/src/components/ProfilePostItem/ProfilePostItem.jsx
- frontend/app/src/components/ProfilePostItem/ProfilePostItem.test.js
- frontend/app/src/components/profilePosts/ProfilePosts.css
- frontend/app/src/components/profilePosts/ProfilePosts.jsx
- frontend/app/src/pages/Profile/Profile.css
- frontend/app/src/pages/Profile/Profile.jsx
Resultado da implementação da seção de posts no Perfil:
Obs: no código, as linhas que fazem a requisição da api para informações do perfil estão comentadas, pois foram criadas informações mocadas apenas para ver o comportamento da tela com os posts. Na issue de utilizar o endpoint para receber os posts de perfil, as linhas serão "descomentadas".
> close issue#49

- backend/app/api/views.py
- backend/app/tests/test_api.py
- db/init.sql
Alem de fechar a issue, o endpoint também informa o numero de seguidores, numero de pessoas seguindo e o numero de posts
close issue#72
> close issue#72

- db/init.sql
> close issue#108

- backend/app/api/urls.py
- backend/app/api/utils.py
- backend/app/api/views.py
As tags que o usuário @eduarda interagiu e que possuem gênero no nome é apenas 1: distopia
O usuário @mancini não interagiu com nenhuma tag que possua gênero no nome.
> Criar e implementar algoritmo de recomendação de livros #44

- frontend/app/src/components/ListItem/ListItem.css
- frontend/app/src/components/ProfilePostItem/ProfilePostItem.css
- frontend/app/src/components/ProfilePostItem/ProfilePostItem.jsx
- frontend/app/src/components/modalPost/ModalPost.css
- frontend/app/src/components/modalPost/ModalPost.jsx
- frontend/app/src/components/post/Post.css
- frontend/app/src/components/profilePosts/ProfilePosts.jsx
- frontend/app/src/pages/Profile/Profile.css
- frontend/app/src/pages/Profile/Profile.jsx
Resultado do uso do endpoint para mostrar os posts do perfil de um usuário:
> close issue#50

- backend/app/tests/test_api.py
Faz o uso do Extract Function para fazer testes com mais eficiencia e remove code smells do tipo comentário 
#119
> close issue#119

- frontend/app/src/components/searchResults/SearchResults.jsx
- frontend/app/src/pages/Pesquisa/Pesquisa.jsx
Exemplo de resultado da pesquisa de usuário feita pelo endpoint da API:
> close issue#60

- frontend/app/src/components/searchResults/SearchResults.jsx
- frontend/app/src/pages/Pesquisa/Pesquisa.jsx
Exemplo do retorno da busca de livros pelo endpoint da api:
> close issue#57
